server:
  port: 8765

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false

      routes:

        # -------- AUTH SERVICE (NO JWT REQUIRED) ----------
        - id: auth-service
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        # -------- FLIGHT SERVICE ----------
        - id: flight-service
          uri: lb://FLIGHTSERVICE
          predicates:
            - Path=/flight/**
          filters:
            - StripPrefix=0

        # -------- BOOKING SERVICE ----------
        - id: booking-service
          uri: lb://BOOKINGSERVICE
          predicates:
            - Path=/booking/**
          filters:
            - StripPrefix=0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # MUST be service name, NOT localhost
      defaultZone: http://eureka:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

jwt:
  secret: Z3lK8s9P0q1R4u7X2b5N8m3C6v9T4r7E1u3P9x6L2q8W4s7D1c5V9b2K4m8J1
  expiration: 3600000
