spring.application.name=eureka-server
server.port=8761

# Eureka server should not register itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Use container hostname instead of localhost
eureka.instance.hostname=eureka

# Optional but recommended settings
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=60000
