spring.application.name=BookingService
server.port=8091

spring.config.import=configserver:http://config-server:8888
resilience4j.circuitbreaker.instances.flightService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.flightService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.flightService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.flightService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.flightService.failureRateThreshold=50
