spring.application.name=FlightService
server.port=8080


logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework.boot=WARN

# -----------------------------
# MySQL inside Docker
# -----------------------------

spring.datasource.url=jdbc:mysql://localhost:3306/microquiz_db
spring.datasource.username=root
spring.datasource.password=Sabiha@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
upload.dir=C:/flight_uploads
spring.jackson.serialization.INDENT_OUTPUT=true





# -----------------------------
# Eureka inside Docker
# -----------------------------
