spring.application.name=Boot7_RedisDemo
redis.host=localhost
redis.port=6379
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/tutorial_db
spring.datasource.username=root
spring.datasource.password=Sabiha@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect