

server.port=8091
#spring.datasource.url=jdbc:mysql://localhost:3306/quizservice
#spring.datasource.username=root
#spring.datasource.password=Sabiha@123
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#eureka.instance.prefer-ip-address=true
#
#
#resilience4j.circuitbreaker.instances.questionService.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.questionService.wait-duration-in-open-state=10s
#resilience4j.circuitbreaker.instances.questionService.permitted-number-of-calls-in-half-open-state=3
#resilience4j.circuitbreaker.instances.questionService.sliding-window-size=10

spring.config.import=configserver:http://localhost:8888 


spring.application.name=QuizService
spring.profiles.active=dev
spring.kafka.bootstrap-servers=localhost:9092 
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer 
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer 
